language: node_js

install:
  - yarn
 node_js:
  - 16.13.0
services:
  - docker

before_install:
  - docker build -t nawaf83/youtube-stats -f Dockerfile.dev .
  
script:
  - docker run -e CI=true nawaf83/youtube-stats npm run test
