language: node_js
node_js:
  - lts/*
os: windows-latest
services:
  - docker

before_install:
  - docker build -t nawaf83/reactapp -f Dockerfile.dev .
  
script:
  - docker run nawaf83/reactapp npm run test -- --coverage

